/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountNav: typeof import('./src/components/AccountNav.vue')['default']
    AddAccount: typeof import('./src/components/setting/AddAccount.vue')['default']
    AppNav: typeof import('./src/components/AppNav.vue')['default']
    EssentialLink: typeof import('./src/components/EssentialLink.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IndexPage: typeof import('./src/components/IndexPage.vue')['default']
    MailCard: typeof import('./src/components/mails/MailCard.vue')['default']
    MailDetailPage: typeof import('./src/components/mails/MailDetailPage.vue')['default']
    MailList: typeof import('./src/components/mails/MailList.vue')['default']
    MailListPage: typeof import('./src/components/MailListPage.vue')['default']
    MainCalendar: typeof import('./src/components/calendar/MainCalendar.vue')['default']
    MainContact: typeof import('./src/components/contact/MainContact.vue')['default']
    MainLayout: typeof import('./src/components/MainLayout.vue')['default']
    MainMail: typeof import('./src/components/mails/MainMail.vue')['default']
    MainSetting: typeof import('./src/components/setting/MainSetting.vue')['default']
    MainTodo: typeof import('./src/components/todo/MainTodo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingMain: typeof import('./src/components/setting/SettingMain.vue')['default']
    SettingPage: typeof import('./src/components/SettingPage.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
  }
}
