/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddAccount: typeof import('./src/components/AddAccount.vue')['default']
    EssentialLink: typeof import('./src/components/EssentialLink.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IndexPage: typeof import('./src/components/IndexPage.vue')['default']
    MailDetailPage: typeof import('./src/components/MailDetailPage.vue')['default']
    MailListPage: typeof import('./src/components/MailListPage.vue')['default']
    MainLayout: typeof import('./src/components/MainLayout.vue')['default']
    SettingPage: typeof import('./src/components/SettingPage.vue')['default']
  }
}
