[package]
name = "entities"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "1.0.0", features = [
    "sqlx-sqlite",
    "runtime-tokio-rustls",
    "macros",
] }
log = "0.4.22"
serde = { version = "1.0.204", features = ["derive"] }
